package com.huawei.sharedrive.uam.user.domain;

public enum AdminRole
{
    ADMIN_MANAGER, APP_MANAGER, ENTERPRISE_BUSINESS_MANAGER, ENTERPRISE_MANAGER, SYSTEM_CONFIG, STATISTICS_MANAGER, JOB_MANAGER, ANNOUNCEMENT_MANAGER,FEEDBACK_MANAGER;
    
}
