/**
 * 
 */
package pw.cdmi.box.disk.event.domain;

public enum EventType
{
    INODE_CONTENT_CHANGE, INODE_COPY, INODE_CREATE, INODE_DELETE, INODE_DOWNLOAD, INODE_MOVE, INODE_PRELOAD_BEGIN, INODE_PRELOAD_END, INODE_PREVIEW, INODE_RENAME, INODE_UPDATE_SYNC, LINK_CREATE, LINK_DELETE, LINK_DOWNLOAD, LINK_PREVIEW, LINK_UPDATE, SHARE_CREATE, SHARE_DELETE, SHARE_UPDATE, TERMINAL_DISABLE, TERMINAL_ENABLE, TRASH_CLEAR, TRASH_INODE_DELETE, TRASH_INODE_RECOVERY, TRASH_RECOVERY, USER_CREATE, USER_LOCKED, USER_LOGIN, USER_LOGIN_FAIL, USER_LOGOUT;
}
